### ISSUE TITLE
Feature Request: Add FREIS to transport helicopters in the editor.

### ISSUE THREAD

**Issue by Sully101x** [phoenixdowngaming/Takistan_Liberation#10]
* title
* this can currently be achieved through zeus with ares
* provides additional vehicle functionality

**Comment by DanAlbert** [comment]
I was also able to do it via the pylon edit menu. That may only be on some helicopters though.

**Comment by Sully101x** [comment]
RGR. I will test this today but I think to make the mission PUB-proof, having the vehicles assigned at mission start is the best solution if it's not too difficult to perform in the editor/settings.

**Comment by stealthypotato** [comment]
due to how vehicles are spawned in liberation, i cannot attach an init string to them on the fly without creating another script on a trigger or in init that calls the vehicle type on a timer or something. Doing this would eat into map and server performance, and at this time other methods are available to attach FRIES to vehicles. For this same reason i cannot change vehicles skins on the fly without additional scripts which i am trying to avoid. For the time being, you'll have to just attach through ace.
